version: '3.1'

services:
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: cabuser
      MONGO_INITDB_ROOT_PASSWORD: cabpassword
      MONGO_INITDB_DATABASE: cabs

  cache:
    image: redis:6.2.6
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - 6381:6379
    deploy:
      resources:
        limits:
          memory: 256M